export type TrustBand = "HIGH" | "MEDIUM" | "LOW";

export type FindingTone = "good" | "warn" | "bad" | "neutral";

/**
 * Information supplied by the user.
 */
export interface ClaimInput {
  event: string;
  location?: string;
  date?: string;
}

/**
 * Media supplied for verification.
 */
export interface MediaInput {
  kind: "image" | "video";
  url?: string;
  name?: string;
  mimeType?: string;
}

/**
 * A single finding produced by any verification module.
 */
export interface ModuleFinding {
  label: string;
  value: string;
  tone: FindingTone;
}

/**
 * Common result structure returned by every module.
 */
export interface ModuleResult {
  score: number;
  maxScore: number;

  summary: string;

  findings: ModuleFinding[];

  /**
   * Things the module could not determine.
   * These will later be used by display.ts
   * to generate a content-centric summary.
   */
  missing: string[];

  /**
   * Warnings or suspicious signals discovered
   * during the module's analysis.
   */
  warnings: string[];

  /**
   * Raw/structured data produced by the module.
   * Kept flexible because every module produces
   * different kinds of data.
   */
  data: Record<string, unknown>;
}

/**
 * Results from all four verification modules.
 */
export interface ModuleResults {
  metadata: ModuleResult;
  vision: ModuleResult;
  weather: ModuleResult;
  evidence: ModuleResult;
}

/**
 * Final result generated by scoring.ts.
 */
export interface ScoringResult {
  totalScore: number;
  maxScore: number;

  /**
   * Score normalized to 0–100.
   * This is for internal calculation/display
   * where needed, not necessarily the main UI summary.
   */
  percentage: number;

  band: TrustBand;

  /**
   * Explains which modules contributed most
   * or least to the final assessment.
   */
  moduleScores: {
    metadata: number;
    vision: number;
    weather: number;
    evidence: number;
  };

  /**
   * Combined missing information from all modules.
   */
  missing: string[];
}

/**
 * Final content generated by display.ts.
 */
export interface DisplayResult {
  verdict: TrustBand;

  /**
   * Main human-readable explanation.
   * This should focus on WHAT the evidence says,
   * not just the numerical score.
   */
  summary: string;

  /**
   * Information shown independently inside
   * each module's frontend box.
   */
  keyFindings: string[];
  modules: ModuleResults;

  /**
   * Final scoring information.
   */
  scoring: ScoringResult;

  /**
   * Important things the user should know
   * before trusting the result.
   */
  limitations: string[];
}

/**
 * Complete request received by /api/verify.
 */
export interface VerificationRequest {
  media: MediaInput;
  claim: ClaimInput;
}

/**
 * Complete backend response returned by /api/verify.
 */
export interface VerificationResponse {
  ok: boolean;

  report?: DisplayResult;

  error?: string;
}